# Appveyor CI configuration for vcpkg project.
#
# Copyright 2018 Hiroshi Miura
#
image: Visual Studio 2017
shallow_clone: false

environment:
  matrix:
    - VCPKG_DEFAULT_TRIPLET: x86-windows
    - VCPKG_DEFAULT_TRIPLET: x86-windows-static
    - VCPKG_DEFAULT_TRIPLET: x64-windows
    - VCPKG_DEFAULT_TRIPLET: x64-windows-static
    - VCPKG_DEFAULT_TRIPLET: arm-uwp
    - VCPKG_DEFAULT_TRIPLET: arm-windows
    - VCPKG_DEFAULT_TRIPLET: arm64-uwp
    - VCPKG_DEFAULT_TRIPLET: arm64-windows
    - VCPKG_DEFAULT_TRIPLET: x64-uwp
    - VCPKG_DEFAULT_TRIPLET: x86-uwp

install:
  - ps: |
      ./scripts/bootstrap.ps1
      ./vcpkg.exe install opencv
      ./vcpkg.exe export opencv --zip
build: off
test: off
deploy: off

artifacts:
  - path: '*.zip'